ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
UPDATE users SET is_deleted = FALSE WHERE is_deleted IS NULL;

ALTER TABLE IF EXISTS addresses ADD COLUMN IF NOT EXISTS is_default BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS addresses ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
UPDATE addresses SET is_default = FALSE WHERE is_default IS NULL;
UPDATE addresses SET is_deleted = FALSE WHERE is_deleted IS NULL;

ALTER TABLE IF EXISTS items ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE IF EXISTS items ADD COLUMN IF NOT EXISTS image_url VARCHAR(1000);
ALTER TABLE IF EXISTS items ADD COLUMN IF NOT EXISTS is_veg BOOLEAN DEFAULT TRUE;
ALTER TABLE IF EXISTS items ADD COLUMN IF NOT EXISTS spice_level INTEGER DEFAULT 1;
ALTER TABLE IF EXISTS items ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT TRUE;
UPDATE items SET slug = LOWER(REPLACE(name, ' ', '-')) WHERE slug IS NULL OR slug = '';
UPDATE items SET is_veg = TRUE WHERE is_veg IS NULL;
UPDATE items SET spice_level = 1 WHERE spice_level IS NULL;
UPDATE items SET is_available = TRUE WHERE is_available IS NULL;

ALTER TABLE IF EXISTS orders ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'PLACED';
ALTER TABLE IF EXISTS orders ADD COLUMN IF NOT EXISTS payment_mode VARCHAR(50);
ALTER TABLE IF EXISTS orders ADD COLUMN IF NOT EXISTS transaction_id VARCHAR(255);
UPDATE orders SET status = 'PLACED' WHERE status IS NULL OR status = '';
